---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: make sure packages installed
  commands:
  - apt install -y git build-essential
- name: pull code
  commands:
  - cd /root/workbench
  - git clone https://github.com/Savemech/ez-cicd-demo.git
- name: build new docker image
  commands:
  - cd /root/workbench/ez-cicd-demo
  - docker build . -t ez-cicd-demo:"${DRONE_COMMIT_SHA:0:8}"
- name: stop docker image
  commands:
  - docker rm -f ez-cicd-demo
- name: start docker image
  commands:
  - docker run -p 80:80 -p 443:443 -d --restart=always -d --name=ez-cicd-demo ez-cicd-demo:"${DRONE_COMMIT_SHA:0:8}"

